#!/usr/bin/env bash
# Build dist/Mirage.app: a thin, ad-hoc signed bundle that runs this checkout's
# venv. Pass --install to copy it to ~/Applications and register it.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP="$REPO/dist/Mirage.app"
ICON="$REPO/assets/icon/Mirage.icns"
BUNDLE_ID="io.github.rebsem.mirage"
LSREGISTER="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
INSTALL=0

usage() {
  cat <<EOF
Usage: scripts/build_app.sh [--install] [--help]

Builds dist/Mirage.app, which launches Mirage from $REPO/venv.
The app stays tied to this folder: rebuild it if you move the checkout.

Options:
  --install   also copy it to ~/Applications/Mirage.app (replacing any old copy)
              and put a Mirage shortcut in this folder
  --help, -h  show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --install) INSTALL=1 ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  BOLD=$'\033[1m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; RED=$'\033[31m'; RESET=$'\033[0m'
else
  BOLD=""; GREEN=""; YELLOW=""; RED=""; RESET=""
fi
ok()   { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$*"; }
warn() { printf '  %s!%s %s\n' "$YELLOW" "$RESET" "$*"; }
die()  { printf '  %s✗ %s%s\n' "$RED" "$*" "$RESET" >&2; exit 1; }

[[ "$(uname -s)" == "Darwin" ]] || die "Mirage.app can only be built on macOS."

VERSION="$(sed -n 's/^__version__ *= *["'\'']\([^"'\'']*\)["'\''].*/\1/p' "$REPO/mirage/__init__.py")"
[[ -n "$VERSION" ]] || die "Could not read __version__ from mirage/__init__.py"

printf '%sBuilding Mirage.app %s%s\n' "$BOLD" "$VERSION" "$RESET"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# ── Info.plist ──────────────────────────────────────────────────────────────
cat > "$APP/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>Mirage</string>
	<key>CFBundleExecutable</key>
	<string>Mirage</string>
	<key>CFBundleIconFile</key>
	<string>Mirage</string>
	<key>CFBundleIdentifier</key>
	<string>$BUNDLE_ID</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Mirage</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$VERSION</string>
	<key>CFBundleVersion</key>
	<string>$VERSION</string>
	<key>LSApplicationCategoryType</key>
	<string>public.app-category.entertainment</string>
	<key>LSMinimumSystemVersion</key>
	<string>13.0</string>
	<key>NSCameraUsageDescription</key>
	<string>Mirage uses your camera to swap faces in real time. Video never leaves your Mac.</string>
	<key>NSHighResolutionCapable</key>
	<true/>
	<key>NSHumanReadableCopyright</key>
	<string>© 2026 Mirage contributors. AGPL-3.0. Face-swap engine: Deep-Live-Cam by hacksider and contributors.</string>
</dict>
</plist>
EOF
plutil -lint -s "$APP/Contents/Info.plist" || die "Info.plist is invalid"
ok "Info.plist (version $VERSION)"

# ── icon ────────────────────────────────────────────────────────────────────
if [[ ! -f "$ICON" && -x "$REPO/venv/bin/python" ]]; then
  "$REPO/venv/bin/python" "$REPO/scripts/make_icon.py" >/dev/null
fi
if [[ -f "$ICON" ]]; then
  cp "$ICON" "$APP/Contents/Resources/Mirage.icns"
  ok "Icon"
else
  warn "assets/icon/Mirage.icns is missing (run make icon); the app will use a generic icon"
fi

# ── launcher ────────────────────────────────────────────────────────────────
LAUNCHER="$APP/Contents/MacOS/Mirage"
{
  printf '#!/bin/bash\n'
  printf '# Mirage.app launcher, generated by scripts/build_app.sh; edit that instead.\n'
  printf 'REPO=%q\n' "$REPO"
  printf 'VERSION=%q\n' "$VERSION"
  cat <<'EOF'
PY="$REPO/venv/bin/python"

if [[ ! -x "$PY" ]]; then
  /usr/bin/osascript - "$REPO" >/dev/null 2>&1 <<'OSA'
on run argv
  set msg to "Run make install in " & item 1 of argv & ", then open Mirage again."
  display alert "Mirage isn't installed yet" message msg as critical
end run
OSA
  exit 1
fi

LOG_DIR="$HOME/Library/Logs/Mirage"
mkdir -p "$LOG_DIR"
exec >>"$LOG_DIR/launcher.log" 2>&1
echo "── $(date '+%Y-%m-%d %H:%M:%S') Mirage $VERSION starting from $REPO"

# Finder starts apps with a bare PATH; add Homebrew for ffmpeg and friends.
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
export PYTHONUNBUFFERED=1

# Drop the -psn_* argument older macOS versions pass to Finder-launched apps.
args=()
for arg in "$@"; do
  [[ "$arg" == -psn_* ]] || args+=("$arg")
done

cd "$REPO" || exit 1
exec "$PY" -m mirage ${args[@]+"${args[@]}"}
EOF
} > "$LAUNCHER"
chmod 755 "$LAUNCHER"
bash -n "$LAUNCHER" || die "generated launcher has a syntax error"
ok "Launcher → $REPO/venv"

# ── sign ────────────────────────────────────────────────────────────────────
xattr -cr "$APP"
codesign --force --deep --sign - "$APP" 2>/dev/null
codesign --verify --strict "$APP" || die "codesign verification failed"
ok "Ad-hoc signed"

printf '%s✓ Built%s %s\n' "$GREEN$BOLD" "$RESET" "${APP#"$REPO"/}"

if [[ $INSTALL -eq 1 ]]; then
  DEST="$HOME/Applications/Mirage.app"
  mkdir -p "$HOME/Applications"
  rm -rf "$DEST"
  ditto "$APP" "$DEST"
  if [[ -x "$LSREGISTER" ]]; then
    "$LSREGISTER" -f "$DEST"
  fi
  # A shortcut next to the code, so Mirage can be opened from the project folder too.
  LINK="$REPO/Mirage.app"
  if [[ -L "$LINK" || ! -e "$LINK" ]]; then
    ln -sfn "$DEST" "$LINK"
  fi
  printf '%s✓ Installed%s %s (find it in Launchpad or Spotlight, or open Mirage in this folder)\n' "$GREEN$BOLD" "$RESET" "$DEST"
else
  printf '  Open it with: open %s   or install it with: make install-app\n' "${APP#"$REPO"/}"
fi
